"""Adde customer name to the customer table

Revision ID: a1c35b821c3c
Revises: b67b0b75de67
Create Date: 2026-02-09 18:55:53.652384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c35b821c3c'
down_revision = 'b67b0b75de67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
